name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run tests
      run: go test -v ./...

    - name: Verify Go modules
      run: |
        go mod tidy
        go mod verify

    - name: Build binaries
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        go build -ldflags="-s -w -X main.version=${VERSION}" -o peaks-linux-amd64 ./cmd/peaks
        GOOS=windows go build -ldflags="-s -w -X main.version=${VERSION}" -o peaks-windows-amd64.exe ./cmd/peaks
        GOOS=darwin go build -ldflags="-s -w -X main.version=${VERSION}" -o peaks-darwin-amd64 ./cmd/peaks

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          peaks-linux-amd64
          peaks-darwin-amd64
          peaks-windows-amd64.exe
        generate_release_notes: true
        draft: false
        prerelease: false
