name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        # Linux
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o peaks-linux-amd64 ./cmd/peaks
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o peaks-linux-arm64 ./cmd/peaks
        
        # macOS
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o peaks-darwin-amd64 ./cmd/peaks
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o peaks-darwin-arm64 ./cmd/peaks
        
        # Windows
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o peaks-windows-amd64.exe ./cmd/peaks
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w" -o peaks-windows-arm64.exe ./cmd/peaks

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          peaks-linux-amd64
          peaks-linux-arm64
          peaks-darwin-amd64
          peaks-darwin-arm64
          peaks-windows-amd64.exe
          peaks-windows-arm64.exe
        generate_release_notes: true
        draft: false
        prerelease: false
